### ISSUE TITLE
[QUESTION] Warning about TLS 1.2 appears with Node v16.3.0 and npm v7.21.0

### ISSUE THREAD

**Issue by darcyparker** [npm/tls-test#1]
# What / Why

When I run `npm install -g https://tls-test.npmjs.com/tls-test-1.0.0.tgz`, I get the "npm notice beginning October 4, 2021, ..."

https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/ says to use the latest version of node and npm - which I am.  (node v16.3.0, npm 7.21.0).  I am using Debian Buster (v10) and nvm 0.38.0.

I expect the connection to be https with tls 1.2.

What am I missing? Others may have same issue, so it could help to add more info to the documentation about this.

**Comment by darcyparker** [comment]
Additional info: I am running Debian on VirtualBox (6.1.26 r145957).  I can serve a simple webserver using TLS 1.2 using express. And I checked in Google Chrome (Dev Tools => Security tab) and pages I am loading are TLS 1.2. So it doesn't appear to be a firewall issue.

**Comment by JeCap** [comment]
@darcyparker 

Check your `.npmrc` files

![image](https://user-images.githubusercontent.com/24272804/130800781-83a86e94-c8ba-44b9-a3c1-1a5fa5827d32.png)

after i changed the registry entry to `https`, it works

**Comment by darcyparker** [comment]
@JeCap - That was it. Thank you. 

My git history showed I was using that .npmrc since 2016... and never noticed it was http:// not https://

**Comment by darcyparker** [comment]
In https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/, and elsewhere, I think its worth adding a reminder to review your `.npmrc` in the docs in addition to recommending using the latest version of node and npm.

**Comment by leifjones** [comment]
@darcyparker (cc: @ethomson) Echoing your suggestion above, it may also be helpful to remind users to check system-level configuration (e.g. [this](https://stackoverflow.com/a/51703987/2199949) for Windows).

Edit: Sorry, @darcyclarke, for tagging you my mistake!

**Comment by darcyparker** [comment]
I did a double take. Another Darcy from the Toronto area... (I grew up in Toronto area... but live in US now.)

**Comment by leifjones** [comment]
@darcyparker Your doppelgänger is also associated with npm and GitHub, to boot!

**Comment by sanjoy0308** [comment]
I am getting this below message when I run 'npm install -g https://tls-test.npmjs.com/tls-test-1.0.0.tgz'
```
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

changed 1 package in 649ms
```
I don't get the message "Congratulations! Your package manager appears to support TLS 1.2."

**Comment by leifjones** [comment]
Hi @sanjoy0308 

I was in the same boat. Are you on Windows? If so, you might want to check the link in my [comment above](https://github.com/npm/tls-test/issues/1#issuecomment-945963098). If not, try checking ~/.npmrc for an `http://`. If you find it, replace with `https://` and try again.

**Comment by sanjoy0308** [comment]
Hi @mrsegen , 

Thank you for the suggestion. I checked your comment and deleted .npmrc and run npm config set registry https://registry.npmjs.org/. But, still no success. I am not getting the message "Congratulations! Your package manager appears to support TLS 1.2."
